### ISSUE TITLE
DB Tables usage

### ISSUE THREAD

**Issue by dev-s** [JC5/firefly-iii#124]
Could you guide us what's the usage of table role, role user and reminder tables in DB?

Can we set a new role and assign to a user? how is reminder works?

**Comment by JC5** [comment]
``role_user`` and ``roles`` are used for a single purpose: to make the very first user who registers an "Site Owner". The site owner can manage currencies.

I added this because users on the demo site were fighting over which currency should earn the use of "$" and which ones would be stuck with "US$" or "AUS$" or "CAN$". 

There is no interface to add roles, or to add users to roles. Adding new roles will not make a difference in Firefly. Deleting the "site owner" role will break Firefly. You can manually give people the site owner role though.

The table "reminders" is no longer used.
