### ISSUE TITLE
Recent cleanup on develop breaks quick link reports

### ISSUE THREAD

**Issue by webenhanced** [JC5/firefly-iii#150]
Recently removed 'startOfMonth', 'endOfMonth', 'startOfYear', 'endOfYear' from app\Http\Controllers\ReportController.php, and they have been renamed in the twig file. The result is broken quick link reports on my setup.

Am I missing something? Or is there more code coming that will resolve this?

**Comment by webenhanced** [comment]
Oops, it is working now. Last time I checked it was broken.
I'll have to find where you moved this to so I can make it custom fiscal year aware. Any comments?
Graham

**Comment by JC5** [comment]
Oh yes!

First of all, absolutely wonderful work on the fiscal year. I'll get right to it in the original issue, #131.

To add custom "rules", please check out file ``app/Support/Binder/Date.php``

The reason this has changed was because Laravel has only limited support for placeholders in ``app/Http/routes.php``. Especially matching something like "{account}" to _a specific users_ account was getting pretty difficult. Matching other things (not models) became impossible with the upgrade to Laravel 5.2

So, there is a new routine in place, which you can find in ``app/Http/Middleware/Binder.php``. This routine finds all {bracket} things and sees if there is a class responsible for binding. If there is, it will call a very special method called "routeBinder" (follow "performBinding"). Please see ``config/firefly.php``.

Do me a favour and do not change "endOfYear" and "startOfYear". I wish to keep both the actual year (for my own sanity) and the fiscal year (for taxes). I would suggest something like "startOfFiscalYear" and "endOfFiscalYear".

**Comment by webenhanced** [comment]
So if I want to add an extra quicklink report in, say "Current fiscal year, all accounts", is it OK to:
1/ add them into the report controller in the old way (start and end dates already calc'd)
2/ or should I add the fiscal helper to the date binder and make 'currentFiscalYearStart' and 'currentFiscalYearEnd' entries in there?
I would have thought (1) above would be more light weight (in terms of object instance numbers) so perhaps a tad (aussie colloquial meaning small amount) quicker.

**Comment by JC5** [comment]
I would suggest option 2, actually. Even though this makes the Date binder more complex, it makes the report controller a little lighter. The calculation has to be done anyway.

**Comment by webenhanced** [comment]
Implemented as per your suggestion.
