### ISSUE TITLE
Refunds negate the expense account and budget

### ISSUE THREAD

**Issue by webenhanced** [JC5/firefly-iii#162]
Is there any way to apply a refund against the expense account (and budget)? I could not find a way.

When entering a refund from a supplier (when returning a faulty product for example), we can use the deposit tab, but the *to* account becomes a new revenue account.

I also notice that the TransactionController ignores the budget_id when coming from the deposit tab.

I have tried using a negative number on the withdrawal tab but that does not seem to work.

So to make changes to Firefly to make the entry of a refund easy, I would think that we would either:-
- allow a negative amount on the withdrawal tab. This is probably easy to do, but the result is not intuitive for the end user.
- add a checkbox on the deposit tab that, when activated, shows the expense-account text box instead of the revenue-account one. We would also need to tweak the JournalRepository & the TransactionController.
- create a new tab for refunds. This would be the cleanest IMHO, with less JS to do.

Without something like this, the only way I have found is to find the original transaction and manually take the refund amount from the total spend amount (as if we never bought it in the first place).

Do you have any plans for this feature?

What is your preferred method of tackling this?

**Comment by JC5** [comment]
I have no plans for this feature, and I'd rather not tackle it at all. It leads to madness.

I personally do not have that many refunds. So, I just let it go ;-).

OK so a budget is 200. If you spend money, you have less to spend on that budget. But what if you _earn_ money? In your case, with a refund. Well either the expenses on the budget go down, or the money available on the budget goes up. I've experimented with both of them, but it all leads to very confusing reports, budgets and overviews.

I've taken the following approach to such things, which is to completely "ignore" it.

- The original expense stays. This is important because a refund could fall into the next month.
- The refund is indeed a deposit, and becomes income.
- Income is moved to savings account. Budget is not changed.

I did this because every line of coding beyond this is trying to "fix" this discrepancy. Intentionally changing budgets, "hiding" expenses, "deleting" deposits, it just feels flimsy to me and personally I try to keep my budgets set in stone. If I have 100,- to spend on electronics and I spend it on something that I consequently return, that's simply "too bad". 

An alternative might be to remove the budget from the original expense ("(no budget)") thereby freeing up the original budget. The refund is a counterbalance to this expense and the original budget remains untouched.
