### ISSUE TITLE
Grouped categories

### ISSUE THREAD

**Issue by webenhanced** [JC5/firefly-iii#163]
I would like to be able to group categories to make it easier to use them.

In my budget spreadsheet (that Firefly will be replacing), I group things together and total the groupings. For example:
- Housing
    - Mortgage/Rent
    - Home Insurance
    - Council Rates
    - Furnishings/Appliances
    - Lawn/Garden
    - Maintenance/Supplies
    - Improvements
    - Other Home Expenses
- Utilities
    - Electricity
    - Gas
    - Phone
    - Cable/Satellite
    - Internet
    - Other Utilities
- Etc

Now I know I could use category names like Housing - Mortgage/Rent, and Housing - Insurance etc, but sub totaling will be hard with that scheme.

I have thought of 2 ways to achieve this grouping:
1. Implement hierarchical categories such that each category has a *parent category* with the top categories having a parent_id of 0. The SQL to get the categories is fairly straight forward with this approach (from memory it was just a clever join to the same table that got them out in the structure desired).
2. Add a grouping_id to each category. This would probably need a whole new table for grouping names with the associated maintenance screen. And the SQL would be less beautiful <grin>.

Both of these would require DB schema changes, and I would need help getting that right with laravel and migrations.

Any thoughts?

**Comment by JC5** [comment]
The previous version of Firefly had this. I've intentionally not included this in the current one.

If you continue, the migrations and laravel are really just part one of a never ending story.

- How deep can categories nest?
- Will you allow parent categories to hold transactions? Because this could be confusing in reports. If Utilities holds 6 sub-categories, what happens when I want to use "Utilities". Can I?
- Continued: If a report summarizes all sub-categories of one main category, the calculation would be off.
- When you create a new transaction, the currently very simple free-format field will need a makeover. Will you suggest categories in the form of "parent - sub"? Or just "sub"? But what about the parent, given the previous question? And what if you want to create a parent AND sub at the same time? I used to use "Utilities/Electricity" with the / as divider but it's a nightmare. Or, there has to be a whole new system to fix this. A dropdown with option groups? But what if the nesting is three levels? Etc. 
- Every single list that mentions categories must also mention the parent category.
- Every single report needs a makeover. Same for charts.
- Could a chart show how the category is part of the parent category?
- Could a parent chart show how its expenses are divided among the child categories? But what if there are expenses tied to the parent as well?
- Can you do /categories/show/xx on a parent? What happens?
- How will categories transition from default categories to parent/child categories? Initially, all categories will be parents. Or will they be "childs" when they have no children themselves?

But I cordially invite you to push on ;-). Some things to think about.

- Method 1 has my preference. Easy to implement, easy to "ignore" (for pages and routines that cannot handle sub-categories yet).
- Every migration is now called "changes_for_vxxx". This is by no means necessary, because you would have to make the choice between "3.7.1" and "3.8.0" and I have no meaningful roadmap yet. But call it something useful. Make sure your migration is absolutely perfect, because any change you need to make later on means a _new_ migration. Firefly's migrations are 40% undo's of previous migrations :P. However, as long as you're in develop it's ok.
- Make baby steps. Start with the SQL. Then maybe the edit/create screens. Then perhaps a list somewhere. Create new pull requests every time. Together we should be able to implement this sensibly.

**Comment by marcoveeneman** [comment]
Hi,

First of all, my compliments for this great project :+1: 

I just tried firefly iii on my local machine and was hoping to find some feature like this request. Unfortunately this is not implemented yet.

I see you guys already have/had some thoughts about gouped categories. Let me bring this topic to your attention with some ideas of mine.

> - How deep can categories nest?

Lets say the maximum depth is 5, which i think is already more then enough. It could also be configurable in the configuration of firefly.

> - Will you allow parent categories to hold transactions? Because this could be confusing in reports. If Utilities holds 6 sub-categories, what happens when I want to use "Utilities". Can I?

No. A category can only have transactions OR sub-categories, not both. If you want to add a sub-category to some category already holding transactions, those transactions will be moved to the new sub-category. The user can then create more sub-categories and move transactions between the sub-categories.

> - Continued: If a report summarizes all sub-categories of one main category, the calculation would be off.

Not if the main category is not holding transactions.

> - When you create a new transaction, the currently very simple free-format field will need a makeover. Will you suggest categories in the form of "parent - sub"? Or just "sub"? But what about the parent, given the previous question? And what if you want to create a parent AND sub at the same time? I used to use "Utilities/Electricity" with the / as divider but it's a nightmare. Or, there has to be a whole new system to fix this. A dropdown with option groups? But what if the nesting is three levels? Etc.

Categories will have the form "parent", "parent - sub" or even "parent - sub - sub - sub". You could have a drop down listing all the categories like:
- Housing - Mortgage
- Housing - Rent
- Utilities - Electricity
- Utilities - Gas
- ...

Creating new categories will be done by splitting the categories on the '-' separator (or whatever you prefer). If no categories exist, you could create a parent category with a sub-category like this: "Housing - Mortgage" .

> - Every single list that mentions categories must also mention the parent category.

Correct. If the category string is too long, you could shorten it by only showing the parent and the last sub category if you want. Hovering the category name will show the full category chain for that transaction.

> - Every single report needs a makeover. Same for charts.

Yes.

> - Could a chart show how the category is part of the parent category?

How about showing only the parent categories. Clicking the parent would show a new chart of only the next-level sub-categories in that parent category. Those are clickable as well.

> - Could a parent chart show how its expenses are divided among the child categories? But what if there are expenses tied to the parent as well?

Expenses won't be tied to the parent. How the expenses in a parent are divided is explained in the previous point.

> - Can you do /categories/show/xx on a parent? What happens?

Yes. It would show everything of all sub-categories there. You could also show everything withing a sub-category by clicking it.

> - How will categories transition from default categories to parent/child categories? Initially, all categories will be parents. Or will they be "childs" when they have no children themselves?

Initially a category will be a child without a parent. Only childs can hold transactions. Once a category is added to a child the first category becomes a parent and all transactions are transferred to the new child.

Let me know what you think.

**Comment by JC5** [comment]
I'll see what I can do. Personally, I've never found nested categories to be actually useful. A separate category for your mortgage is pointless. Unless you pay multiple mortgages, gas bills, electricity bills and other utility bills, you don't actually need separate categories to tell them apart. The beneficiary can tell you that. Likewise with costs for groceries (food, personal, market, hello-fresh), going out (drinks, eating out, ordering in, alcohol) and other categories of expenses: if you require so many distintions in your expenses, that you need sub-categories to keep them apart you have a bigger problem than a lack of granularity.

Of course, I have several categories that could be reasonably clumped together under groceries, going out, hobbies, etc. But since it's for my personal financial management, I really don't need a "Hobbies" parent category to know what "Woodworking materials" might actually be about. It's all fluff.

A "configurable limit" means it'll have to be built to be infinite anyway.

I like the solution of not putting anything in the parent category.

Rather than implementing parent/child categories, I will focus my effort on decent reporting for categories (and budgets). The current overview(s) for categories are single category only. Other reports include _all_ categories. There is no reason why the current set of reports could not be extended to include only specific categories or budgets. You can build your own groups of categories and report on "housing" or "utilities", as you see a combination of categories, budgets and/or accounts.

I know every other financial system and website has grouped categories but I never saw the point.

**Comment by marcoveeneman** [comment]
I think i get your point about categories not being usefull. Extending the reporting feature could give the same result as grouped categories if used correct.
