### ISSUE TITLE
PHP 7.0

### ISSUE THREAD

**Issue by JC5** [JC5/firefly-iii#165]
I intend to move to PHP 7.0 once 3.7.0 is released. Thoughts?

**Comment by RC5** [comment]
For those who suffer from php7 composer installation issues, because php5 dependencies are declared. You can manually install composer by executing as follow:

(download composer)
# curl -sS https://getcomposer.org/installer | php -- --install-dir=bin

(run composer install)
# /bin/composer.phar install

More info here
https://getcomposer.org/download/

**Comment by AxisNL** [comment]
I'm no developer (but a sysadmin). Moving to PHP7 already is perhaps a bit soon,a lot of people will not be able to get php7 installed on their system yet. I had to hack a server outside of my puppet environment, to be able to install php7. It worked though, although it takes me 5 minutes to set up a centos7 machine with php5, and installing php7 took me about 2 hours of hacking. 

There will be people with shared hosting package, that will not be able to run firefly within the next 6 months because of this choice I guess, which is a shame.

**Comment by JC5** [comment]
I know. But I remember how long it took for everybody to move from PHP 4 to PHP 5, and I don't want to be a part of it.

**Comment by RC5** [comment]
I'm very satisfied with plesk multiple php support which includes most important php versions and i highly recommend for system administrators and developers
