### ISSUE TITLE
Missing a cent

### ISSUE THREAD

**Issue by AxisNL** [JC5/firefly-iii#205]
This is strange.. While reconciling my accounts, I run into a strange transaction:

Account type	Asset account
Amount	(€31.94)
New balance	(€50.33) → (€82.26)

According to my calculator (and Excel), -31.94-50.33 = -82.27, not -82.26.

**Comment by AxisNL** [comment]
Hmm.. and continuing on my transactions, I see some add a cent too much, and some have one cent too little. Eventually, the end balance is okay, but I still fill it's a bit strange, like there's some rounding somewhere. (Even though we only work with 2-digit numbers??)

**Comment by JC5** [comment]
There is some rounding, although it's very rare. ``floatval()`` is used rarely, and usually only when the data is displayed, not used. For example in charts and other displays. That's probably not the source. ``round($amount, 2)`` is used sparingly for the same reason.

The BCMath module is set at 2 digits and should not lose accuracy anywhere since everything is basic arithmetics. 

However, there is the possibility that I have forgotten a ``bcscale()`` somewhere. I will look into it. 

- Could you check which transactions differ a cent?
- In the database as well as in the view?
- Is it an imported or created transaction?
- Any views that disagree on the amount of the transaction?

**Comment by JC5** [comment]
I've removed all the floatvals, and I've expanded the bcMath to 4 digits instead of 2. I just recently learned that bcscale(2) doesn't _round_ numbers at 2 digits but rather, stops calculating once 2 digits have been reached. This may have resulted in inaccuracies.

Let me know when other problems pop up.

**Comment by JC5** [comment]
FYI, in the next version of Firefly

![audit](https://cloud.githubusercontent.com/assets/5889984/14384679/9bfce046-fd9c-11e5-8ea6-8921810d3513.png)
