### ISSUE TITLE
Setting an opening balance of "0" clears the opening balance date

### ISSUE THREAD

**Issue by xnyhps** [JC5/firefly-iii#214]
If I set an initial balance of "0" and save the account, the date I set is either not saved or doesn't appear. When the form loads again, the date field and balance fields are empty. I don't know if this is expected behavior, but it confused me a lot.

**Comment by JC5** [comment]
This is indeed expected behavior.

**Comment by marcoveeneman** [comment]
I see this issue is closed, but after setting the initial balance to 0 it's not possible to change it later on. At least that's what i'm experiencing on the demo site. This looks like a bug to me.

**Comment by JC5** [comment]
I know. I saw an (unrelated) bug report coming from you, which should be fixed by the way.

But to explain this issue: a transaction with an amount of 0.00 has no effect. There is no money going to anywhere, coming from anywhere. The system will not accept it, because it doesn't do anything. It's fluff, it's empty.

I have spotted the bug you are describing and it does exist, and it is very real. When you edit an account and set the opening balance to "not 0.00", it will _not_ be saved. I've pushed a fix to the demo site.
