### ISSUE TITLE
Link things to specific account

### ISSUE THREAD

**Issue by matthijsvdr** [JC5/firefly-iii#226]
I recently installed Firefly, and added everything to see how things work ect. Now i currently have several bank accounts and each account has its own budget. 

Now i could add budgets like Account1 -> budget1
But it would be nice if budgets could be linked to a specific account.

Same goes for other things, some bills are expected to go from account1 others from account2 (eg costs of the account it self, however the text amount and description are the same for all accounts so 1 bill matches every transaction for all accounts)

**Comment by JC5** [comment]
The exact functionality as you describe it, is not on my list of things to do. Forcing budgets and categories (and bills and rules and what else there might be) to specific accounts is a heck of a lot of work to implement in a user friendly way, while I feel it is ultimately up to the user to make sure that the right things are connected to the right accounts.

As for budgets, they should be "global", since Firefly III has been designed to run a _single_ financial plan. Even the addition of "shared accounts", which (mea culpa) I needed myself is flakey. Exactly because of what you are asking for: budgets, categories and accounts run into each other, and various tricks are required to make it all work. It's already messy, financially speaking.

So, linking the right budget to the right account is something you must do yourself. If they have the same name (for example "Groceries"), they should be the same budget. Not "Groceries account 1" and "groceries account 2" because that completely defeats the purpose of budgeting.

As for your second point. Bills are matched on two things: words in the description, or words in the destination account. For example, [internet] [comcast] could match on the description "Internet connection" destined for expense account "Comcast". Likewise, the _source_ account could be included in the search. This means that [account1] [internet] [comcast] would not match a transaction going from account2 to "Comcast" with description "Internet connection".

I will make a note and extend the bill-related routines and pages to include the destination account. This will make it easier to match bills correctly, especially for banking related costs.

On the long run, I expect the "rules" page to take over this functionality. You can now make rules (this is fairly new in Firefly III) which have "actions". For example, rules can automatically set the category or indeed the budget. In the future, they might set the related "bill" as well.

To answer your original question: if you wish to link account1 to budget1, you must enter the transactions correctly. Firefly will not do it for you.

**Comment by matthijsvdr** [comment]
Good to see you don't just say no, but you gave it some thought :)

Because Firefly work with a "single financial plan" its hard to place 3 financial plans into one Firefly account. But this could be spread across 3 Firefly accounts.

Person1
Person2
SharedBetween1&2

In this case 1 and 2 would have there own firefly account, and SharedBetween would be something like a "floating" account that can be accessed by 1 and 2 with a fast account/showme switch or something. 
This way all firefly accounts have a single financial plan, but they can still be shared between users, and in the end achieve the same thing.

Anyway just an idea :)

**Comment by matthijsvdr** [comment]
I also tried the example you gave like:  [account1] [internet] [comcast]  but that bill then matches on nothing.

**Comment by JC5** [comment]
I've been thinking about that last one as well.

The current shared accounts already make it difficult to distinguish between expenses, transfers and earnings. Moving money to a shared account is an expense, because it's not your money anymore. But getting money back from that same account, it's not really an income either.

Most reports handle this (quite well, even if I say so myself) by treating any account not selected as an "external" account, thus making transfers to it an "expense".

Firefly III currently has two problems: it's way too easy to "hide" expenses outside of budgets and it's too hard to distinguish between shared accounts and your own accounts. Two things that need a good thinking over to be handled well. Your solution is a very good one to fix the "shared accounts"-problem.

As for the [account1] [internet] [comcast] thing, it's not yet implemented, it's merely an idea you gave me to solve your problem. I'll tag this issue for 3.8.1.

**Comment by JC5** [comment]
I'm closing this to get to the milestone, but I've saved the ideas for later.
