### ISSUE TITLE
Mass removal of transactions

### ISSUE THREAD

**Issue by Amain** [JC5/firefly-iii#241]
Hi,

It is possible to delete transactions, one-by-one. Consider the case where I would like to revert an import that went wrong. Or simply want to remove multiple transactions. I would need to delete many transactions, manually, one at a time. This, of course, is cumbersome. 

I would like to see an option introduced which allows to delete larger batches of transactions in one go. Preferably with the buttons / checkboxes controlling: select all, deselect all, or select/deselect individual transactions. Together with issue #240 (Transactions can't be filtered using date filter control), this would give great control over transactions. Extending the filtering capabilities with free text search would further improve this.

Regards,

Amain

**Comment by JC5** [comment]
I feel that a mass delete may not be hard to implement, and I'll look at it for sure!

**Comment by JC5** [comment]
Will be included in the next version.

**Comment by Amain** [comment]
Great!! And thanks!

**Comment by FrodeMMeling** [comment]
How is this implemented? After a import, I got an error and would like to revert it. How to do that without manually hacking database?

**Comment by JC5** [comment]
The import routine also compares new entries to the content of deleted transactions. This is to make sure that previously imported and deleted transactions (many banks feature "meta"-lines in their CSV-files) won't be imported again.

If you want to force the importer to re-import such line, you must forcibly remove them from the database.

**Comment by FrodeMMeling** [comment]
Ok. My problem was that many transactions where not imported due to "duplicate" issue.. date, description and amount is the same.. so I need to reimport all failed..

this is something called micro-saving. Its like everytime I use the debetcard, $0.50 goes to a savings account.. These are threated as duplicates it seems on import. there should be a way to to use "auto external id" when importing or something, so this do not happen.. Or a "force duplicates" option on import. I know my bank-statements are not duplicate when importing first time.

**Comment by JC5** [comment]
Unfortunately, if the transactions have no unique identifier of any kind in the CSV file, Firefly III won't be able to import them.
