### ISSUE TITLE
About reports

### ISSUE THREAD

**Issue by AxisNL** [JC5/firefly-iii#255]
When I click on the help icon for reports, it implies I can choose three reports:

```
There are a few options

Default financial report

Will tell you how you are doing. Global overview.

Transaction history overview (audit)

Will tell you how you accounts have gotten to their current point. Shows ALL available meta data. Can help you track down errors in your finances.

Categories, budgets and bills overview

Will show you how you've been doing. Over-budgeted? Wrong categories?
```

However, I can only select the first two reports, no the third one.

I was looking for a way to find out how much I spent per category last year, but I haven't found a way yet. In the default financial report, the graph shows how much I spent per category, but I have the make an estimate of the y-axis value. If I hover over the category, I can see how much I spent per month, but not the total (I'd have to manually add the per-month values to get a total).

Solutions?

**Comment by AxisNL** [comment]
Ah, I found a way. I went to the homepage and changed the period to last year. Then I can see the amounts I spent per category. Still, I think the total should be shown somewhere (perhaps in the mouse-over screen that shows the per-month amounts).

**Comment by JC5** [comment]
The third report is / was a work in progress. I have to think exactly about what I want to show, and find a better way to show it.

The current reports lack "progress". Questions such as these are very hard to answer:

- Am I doing better than last year?
- What exactly do I need to see in a report to define or determine "better"?
- Am I spending money as fast as I was last month?
- Did my expenses on X go up, down, or stayed equal?
  - X can be a budget, category, account, tag, etc.
  - Given a certain period.
  - Grouped by a time range.
  - Would be like: show me how category Groceries are doing, 2015-2016, grouped by week.

Your questions are becoming more and more relevant since people are putting more data into Firefly, and the default reports (check out the "default financial report" and select a year's worth of data.. ugly!) are not up to the task.

I'm working on a solution!

**Comment by JC5** [comment]
The category report is now present. A budget report will follow.
