### ISSUE TITLE
Import does not handle csv with debit and credit columns

### ISSUE THREAD

**Issue by mondjef** [JC5/firefly-iii#307]
csv file contains the following layout...

Date, Transaction Details, Funds Out, Funds In

Based on whether an amount is either in Funds Out or Funds In column should trigger the setting of the Account to or Account From if it can be imported.  Right now you can only choose one of the columns as the 'Amount' column and transactions with no value in this column are not imported at all.

**Comment by JC5** [comment]
This isn't really something the CSV importer is built for. Although rules are possible, to a point, the CSV file should contain lines that hold all information necessary.

Firefly can compensate for missing stuff up to a point, but especially the amount is really necessary to actually create a transaction. It might be possible to set both fields to "Amount" but that is something you'll have to try.

Which application exports the data in this fashion?

**Comment by mondjef** [comment]
my stupid (but cheap) Canadian bank, Presidents Choice Financial.  They offer csv, qfx, aso...all with different levels of details for the same transactions.  I could probably run the qfx through a Python qfx parser to spit out a csv file for firefly to consume.  Flagging both columns as 'Amount' does not work, however if I merge these two columns before hand changing the Funds Out column values to negative I can import properly.

**Comment by JC5** [comment]
It should not be difficult to write a fixer, just like already existing ABN Amro and Rabobank ones. As far as I can tell now, the amount in/out is always in the same spot: columns 3 and 4. I've found some help pages but their export format is, frankly, abysmal.

Does the center column with a description also contain some opposing account information?

**Comment by mondjef** [comment]
I agree their export options as a whole are very sub standard...otherwise a great bank though.  They do offer .qfx and I was thinking of an automated work around on my end and I had the idea that it would probably be very easy to add .ofx and .qfx support simply by parsing these files to a .csv in the background prior to continuing with the import.  For example there is a Python module that can parse these standard files and it would be very easy to output in a .csv format.  (I am a Python guy more than I am PHP....).  Maybe something similar exists in PHP too but I am not sure.  

Anyway, to answer your question...no the description does not contain opposing account information as a general rule of thumb but you will see transaction it does in some sense.

Here is an example to give you more of an idea....

![image](https://cloud.githubusercontent.com/assets/22079851/18396329/114f0992-7691-11e6-9bd0-332986e0b03a.png)

The transfer in/out is usually transfers between different accounts with the same bank between myself and my wife.  (another issue, when I import my bank transactions I have no way to change these transactions to 'transfer' type of transaction and not sure how things will work when I import transactions from the opposing account with respect to duplication).

**Comment by JC5** [comment]
I'm not sure I can do much with the descriptions, in regards to the name of the account it is supposed to belong to. Tell you what I'll build, given this particular layout.

A fix thing (a checkbox at the start of the import that will "join" the amounts correctly into a single column, as well as a "duplicator" that will duplicate the "transaction details" column. This way, you can use one column as the description, and the other one to pick out opposing accounts.

Sounds like an idea?

**Comment by mondjef** [comment]
I will see if I can follow you....

When I import transactions I have the choice to choose the account that these transactions pertain to...default account.  By 'joining' the amounts I assume you mean into one column with some values positive and other values (Funds out) negative.  I did this manually to a test import file and firefly does then put the default chosen account as either the 'from account' or 'to account' based on the negative or positive value so that part works.  The duplicator part I don't quite follow completely but think it would go as such... as an example, the line with Insurance Johnson would some how correspond to an expense account (the opposing account) maybe based on my rules right?

With respect to the 'Transfer out/Transfer in' transactions I have done some tests and could for these transactions run a query on the DB to switch them over then in firefly select the proper opposing assets account.  Not clean but it works.  As I get familiar with the layout of the code I will try to implement/share things as I need them...but for now I am a bit lost and green so I appreciate your assistance.

**Comment by fuf** [comment]
I've been trying to tackle a similar issue today. 

My own quirky bank exports CSV files like this (simplified):

![before](https://cloud.githubusercontent.com/assets/1835637/18481591/973fdc48-79d4-11e6-8d82-1c0709a2548f.PNG)

Initially I tried setting columns C and D both to "Amount" during the import configuration (as suggested above). This didn't work because the importer sees an empty value in, e.g., C3 and skips to the next row, missing the value in D3.

Instead, this works for me:
1) Convert "debit" amounts to negative numbers
2) Merge credit and debit columns

Result:

![after](https://cloud.githubusercontent.com/assets/1835637/18481729/2b972572-79d5-11e6-9d80-487e41f927aa.PNG)

Adds an extra few steps to the import process but still fairly straightforward.

The much bigger issue for me is that after a successful import I am left with a long list of transactions with "Unknown revenue account" and "Unknown expense account". 

The only relevant data to determine the correct account is the "Description" text, e.g. the string "GOOGLE *ADWS" always appears in payments for Google PPC. 

I notice there is a rule trigger for "Description contains..." that lets me successfully capture all transactions to Google PPC by entering this string. 

However, there doesn't seem to be a corresponding "Action" that will let me assign this transaction to a particular expense account. I can add tags and categories, but not accounts...

The rules feature would be hugely useful for me with two additions:
1) Allow assigning to account as an "action"
2) Some kind of "Apply rule to existing transactions" button that would retroactively assign accounts / categories / tags to transactions already in the database.

Currently I am trying to achieve the above using SQL queries directly, but this is not ideal.

p.s. I notice that imported transactions seem to default to Euros (€) even though I've set a different default currency on the currency screen.

p.p.s I am loving Firefly so far! Really impressive stuff.

**Comment by JC5** [comment]
Thanks for all the feedback!

To explain the "duplication": The transfer details column would be duplicated, and when importing this column would appear twice, with the same value in it. Column 1, and column 2:

1. Column 1 should be assigned the "description"-role. This is similar to what you're doing now.
2. Column 2 (again, containing the exact same information as column 1) should be assigned the "opposing account name" role. Then you can map each value to an existing expense account. To do so, make sure you use the checkbox at the same place where you would set "opposing account name". This allows you to fine tune the destination account without using rules.

That way, column 1 would be the description and allow you to make rules to trigger on the description. Column 2 would do what you suggest rules to do: change the opposing/destination account.

The two amount columns would be joined into one column, containing negative and positive amounts, depending on their position.

Let's see if I can summarise:

- A piece of code in the folder app/Import/Specifics should handle the duplication and amount "unification". This alone should simply importing greatly.
- There should be a way of mass applying rule(groups) to a selection of transactions. Where this selection has to be made has yet to be chosen, but two spots come to mind.
  - At the bottom of ``/transactions/withdrawal`` (and the lists for deposits and transfers) where there are checkboxes already.
  - At the bottom of tags lists (``/tags/show/xx``) which would be useful since imports are tagged as a group any way.
  - Text should be added to the import routine or to the help pages to help users manage this.
- "Rules" needs some new actions:
  - The ability to set the destination account. This needs some thinking because if the matched destination account is an expense account while the transaction is a deposit, the rule would fail. But nevertheless.
- The default currency thing is a bug. I've found it and I will fix it.

Please don't hesitate to append to this list!

Thank you both :)

**Comment by fuf** [comment]
Hi JC5,

I think your planned additions will help a lot :)

A way to mass apply rules to a selection of transactions sounds great, but in my case just a button to apply the rule globally across all transactions (that match the pattern) on the rule page itself would be ideal.

I realised I can try the duplicating columns thing myself: I duplicated the "Description" column in my CSV so that I could assign one to "Description" and the other to "Opposing account name" per your suggestion. 

It works and I can successfully map transactions with identical descriptions to particular accounts, which saves a lot of time.

In my case it's not a perfect solution, however, because a lot of my transactions include a date or reference number in the description along with the client name, so they get treated differently and I have to map them separately.

Two typical transaction descriptions:
RANDOM COMPANY LTD INVOICE 1580 RP796990900 207174     10 08SEP16 17:24 
RANDOM COMPANY LTD INVOICE 1577 RP796857700 207174     10 08SEP16 17:21 

This is why the "Description contains..." pattern in the Rules is so handy, because I can just use "RANDOM COMPANY" to grab the whole set of transactions. I just need the additional step of then being able to assign them to the RANDOM COMPANY account.  :)

**Comment by mondjef** [comment]
I have the same view as fuf....I can see it being very handy to have the ability to set rules that determine the destination account both during import as well as the ability to apply any rules at any time retro actively to existing transactions if need be.

For the transfers between accounts issue I have come up with two work arounds, both less than ideal.  I either identify these transactions after the import and run an update query against database to change them to 'transfer' type transaction then go into firefly and set the destination/source account.  The other way would be to have both a revenue and expense account for 'transfers' which would be used as the opposing accounts for these transactions and would or should cancel each other out but its not really the right way it should be done.

**Comment by JC5** [comment]
Everything but issue #321 is now present in FF. I'm closing this one.

**Comment by lastlink** [comment]
firefly seems to have great support for debit and credit. I made a csv parser in dotnet to help format bank statements for 2 major us banks. I was using environment and variable files so there's a lot of room to customize. https://github.com/lastlink/firefly_tools. I allow the ability to do a search to convert accounts and also create a budget column from keywords.
