### ISSUE TITLE
Concept of 'Transfers' and how the are treated by firefly

### ISSUE THREAD

**Issue by mondjef** [JC5/firefly-iii#312]
This could be me not entirely understanding Firefly at this time but I feel that 'Transfers' transactions are not really treated properly by Firefly.  My understand of Transfers is an exchange of money between asset accounts...whether this is between bank accounts, bank account and credit card or line of credit (payment), or ABM withdrawal (transfer of money to your wallet...which should be another asset as that money is an asset until it has been used on expenses which would need to be added manually in firefly).

So here goes my proposal...Transfers should for the most part be ignored by Firefly when producing expense/revenue reports or budget reports as they only represent intermediate transactions for which no true revenue or expense has been realized.  The only purpose they serve in Firefly would be to maintain firefly asset account balances in sync with the actual balances.  If firefly treated transfers in this fashion there would be no need to use balancing-act tags.

If I am missing something please let me know.  I have used a hacked up version of Pear Budget (spread sheet version) for two years that worked well but not very accessible being a spread sheet.  Pear Budget essentially does not care about transfers as it does not attempt to keep balances of any accounts as it only handles the budget planning part so my thinking might be bias from its concepts.  If you want to have a look at the spread sheet if curious let me know and I will post.

**Comment by JC5** [comment]
Cash withdrawals are not transfers. Firefly assumes the money is gone, as I do myself when I take out cash. Hence, it is a withdrawal, and not a transfer. You could of course create an asset account and call it "wallet". ;)

Transfers _are_ ignored in most reports, assuming you include both accounts in question. The  the report is drawn from the perspective of the account(s) included. If the money is transferred to an account that is also in the report, it is still "there". If you transfer money away from the account(s) included in the report, it is "gone"

Balancing act tags are used by me because I use them to "balance out" transactions that have _no_ budget. My month starts with exactly the amount I have budgeted (I transfer money back and forth regularly, and it does not influence my reports because I include the accounts involved). For example, 1000,-.

If I spend 400,- on something expensive I would either have to:

- Expand a budget and add money to the account to compensate
- Get a negative balance because the remaining 600,- could not cover my 1000,- budgets
- Balance the expense with a transfer of 400,- from my savings account.

I always take the third option. Any expenses outside of budgets have a transfer from my savings account to compensate. The balancing act tag is used to mark these expenses.

Mind you, this is not a perfect solution, even for my own use case. There's only so many times I can call a tag "new gadget" (since it only accepts 2 transactions, 1 transfer and 1 expense) and it doesn't make my reports any clearer.

But that's the idea behind it, in any case. Does it make it any more clear?

**Comment by mondjef** [comment]
ok I looked at some other reports and yes you are right the transfers are there/no there as you explained above.

The chart I was referring to is on the Dashboard and is a breakdown by category.  I have an amount showing in this chart as 'no category' and the entire amount is related to all my transfers as I have not assigned a category to them.

![image](https://cloud.githubusercontent.com/assets/22079851/18527873/852f982a-7a94-11e6-9081-1c69305f8084.png)

I can certainly live with it, its just does not look right to me.  I could simple assign them a 'Transfer' category and ignore them in this chart as a workaround.

Thanks

**Comment by JC5** [comment]
It should not display such transfers, and I see that my Firefly does this too. It's a bug, plain and simple.
