### ISSUE TITLE
Creating transaction randomly fails

### ISSUE THREAD

**Issue by jimmycleuren** [JC5/firefly-iii#327]
Every now and then, I get an error page when creating a transaction. If I check the logs, it shows the following error:

[2016-09-23 19:47:24] production.ERROR: Illuminate\Session\TokenMismatchException in /var/www/firefly-iii/bootstrap/cache/compiled.php:3227
Stack trace:
#0 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/firefly-iii/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
...

**Comment by JC5** [comment]
A token mismatch exception happens when something broke in your session. Try deleting all your cookies, and logging in and out again.

It can also happen when you submit a form on one tab, and then try to submit another one on a second tab.

The error comes from the framework _below_ Firefly III, called Laravel. There's not much I can do, I'm afraid.

**Comment by jimmycleuren** [comment]
Yeah, I know. The weird thing was that I only had 1 tab open and could continue afterwards without having to log in again.

**Comment by JC5** [comment]
Is it still happening? Is it always when you create a new transaction?

**Comment by jimmycleuren** [comment]
Meanwhile I've updated to version 4 and still got the error today. It happens only when creating a new transaction.

**Comment by jimmycleuren** [comment]
Just got the same error when updating a transaction as well.

**Comment by JC5** [comment]
How do you store session data? In your ``.env`` file, what is your ``SESSION_DRIVER``?

**Comment by jimmycleuren** [comment]
Sorry for the late response.

SESSION_DRIVER=file

**Comment by JC5** [comment]
Mmmm. That can't really be the problem. The ``file`` driver should work just fine. You could switch to ``database``, just to see what happens.

**Comment by luckylj** [comment]
I am having the same problem and it happens to me everyday when adding or modifying transactions. I have to clear cookies and history in my browser in order to work. Wish there was a permanent fix to this so that I have to clear browser each time.

**Comment by JC5** [comment]
Try the following when this happens:

Visit ``/flush``.

Run ``php artisan cache:clear``.

I believe this happens when something in your session changes while you are using it. When a cache is cleared half-way or when something else is updated.

Refreshing the page should work as well.

Otherwise, the session is cleared too fast for Laravel (the underlying framework) to handle, or it is not stored at all. 

I'll see if I can at least catch the error internally, and store some debug information.
