### ISSUE TITLE
Creating new account fails

### ISSUE THREAD

**Issue by Cheaternl** [JC5/firefly-iii#340]
Version 3.8.0

An exception has been thrown during the rendering of a template ("Trying to get property of non-object") in "./layout/default.twig" at line 190.

I managed to create myself a new user by manually set the string value on line 190 to 'EUR' so I can continue for now. Just reporting this to have it fixed in a later version.

**Comment by JC5** [comment]
Did you run the migrations? How many entries are there in table ``transaction_currencies``?

**Comment by Cheaternl** [comment]
You are right. I did miss a step in the installation process. :-)
php artisan migrate --seed --env=production

Maybe add a check around these database table fetches when they return 0 records, to show a message to check the installation docs?

**Comment by JC5** [comment]
Glad to hear you found it!

I thought about such a thing indeed, but it became difficult to predict exactly _when_ the tables would first be queried, and by which page. It used to be the home page, but when certain code kicks in just before that moment, the warning would be "too late". This kept happening and I had to move the warning around, taking into account various situations through which you could still miss it and get a weird error instead of a nice error. 

So it became a massive "thing" for the mere sake of checking the installation status. Luckily, it doesn't happen too often so I've decided to drop it for the time being.

**Comment by Cheaternl** [comment]
I understand your problem of handling such errors in a broad way.
However, in such case an important entity cannot be fetched from the database, you could redirect the user to an error page with just only that error message. 
Now I see an error page which most of the users need to research how to resolve it (like I did now :-) )
