### ISSUE TITLE
"Bills Paid"-sum does not respect current date range

### ISSUE THREAD

**Issue by bnw** [JC5/firefly-iii#341]
I noticed that when I select a month in which no transactions have been made, the "Bills Paid" amount in the dashboard can be > 0.
This happens because BillRepository::getBillsPaidInRange takes into account all bills whose periods intersect the current date range. 

For example, lets say I have a yearly bill, starting in 2016-01-01.
I pay that bill in March. Now, the amount of the bill will be added to the "Bills Paid"-sum for every month between March and December. 

Is this intended behavior?

**Comment by JC5** [comment]
Yes and no.

It is, because technically the bill has been paid in the period the bill is valid: the year. But no, it should not register for March because there is no transaction relevant for the current view. 

I never noticed this because I'm currently not using yearly bills. These things can pop up every now and then.

I'll look into it and see if I can get it fixed. I believe ``getBillsPaidInRange`` isn't used often, so it should not be difficult to fix.

**Comment by JC5** [comment]
I've changed some of of my personal insurance policies to be paid yearly and I've created a bill to match this. I will run into this problem soon so I should be able to fix it soon as well.
