### ISSUE TITLE
Importing firefly csv file error

### ISSUE THREAD

**Issue by AxisNL** [JC5/firefly-iii#365]
I've got a 3.8.4 instance running and I just installed a new pristine 4.1.1 instance using a separate new db. Since I have no idea how to upgrade the db, I thought a CSV export and import should perhaps do the trick as well. 

I exported the CSV and on the 4.1.1 instance tried importing it again, using the csv file and the configuration file exported earlier. That returns an error that doesn't tell me much. Any tips?

Firefly III ran into an error: Undefined index: column-mapping-complete
The error was of type "ErrorException".
The error occured on/at: Wed, 26 Oct 2016 18:56:07 +0000.
This error occured in file /home/domains/hongens/firefly4/app/Import/Setup/CsvSetup.php on line 303 with code 0.
The error was encountered by user #1, 
The IP address related to this error is: 192.168.128.14
The full stacktrace is below. If you think this is a bug in Firefly III, you can forward this message to thegrumpydictator@gmail.com. This can help fix the bug you just encountered.
If you prefer, you can also open a new issue on Github.
The full stacktrace is below: <empty>

**Comment by JC5** [comment]
Alright, that is going to be though. Since the migrations have moved around and the code has changed a lot, it's going to be pretty difficult to upgrade unless you do it manually.

The CSV import has unfortunately also changed between 3.8 and 4.1. 

I've been searching online for a script but I can't get anything to easily migrate from the old to the new version. I'm sorry, I can't help you migrate :(
