### ISSUE TITLE
Problem with Transfer from Piggy Bank account to another account 

### ISSUE THREAD

**Issue by HomelessAvatar** [JC5/firefly-iii#378]
When doing a transfer from an account with a piggy bank to another account, I select the said piggy bank for the transfer.

After I save the transaction, the transaction is not associated with the piggy bank.
When I edit the transaction, the piggy bank selection just shows (none) is selected, It does not save my selection even through editing.

The money is also not removed from the piggy bank, because it has not been associated with the transaction.

As a side note; does the transaction descriptions, tag names, etc. accept latin extended characters?

**Comment by JC5** [comment]
The connection may not have been saved, when the amount transferred away was bigger than what was in the piggy bank. I'll add some log things so you can verify this.

I will change firefly so it will reflect what this method is for:

- When you add or remove money from an asset account, you can pick a piggy bank. If the money goes to the account with the piggy bank, the money is added to the piggy bank. Otherwise it is removed.
- When the amount added is over the target amount of the piggy bank, only the difference is added.
- When the amount removed is more than the current amount in the piggy bank, only what is in the piggy bank will be removed.

This connection between a transaction and a piggy bank is a one-time event and cannot be edited or updated; even though Firefly supports this (this is wrong, and will be changed). 

This function has been mediocre at best until now and I will make sure it is updated and improved.

As for the latin extended, everything related to firefly is in utf-8. If your database is utf-8 too, you should be fine.

**Comment by HomelessAvatar** [comment]
Thanks for your help.
I've tried this again with your fix.

`[2016-11-06 15:26:29] production.ERROR: No piggy bank repetition on 2016-11-04!`
`[2016-11-06 15:33:11] production.ERROR: No such piggy bank!`
`[2016-11-06 15:34:01] production.ERROR: No piggy bank repetition on 2016-11-04!`
`[2016-11-06 15:36:11] production.ERROR: No piggy bank repetition on 2016-11-06!`

So the amount in the piggy bank is 1250 and is at 100%.
First, I tried to do a transfer from the account with the piggy bank to another account for 800.
Got the first error.
Deleted this transaction, tried with the same kind of transfer with the full amount, and got the second and third errors in the log.
Deleted this transaction too, and edited the piggy bank to see if something was off.
Tried the transaction again with 1250, still got the error.

Is there anything else you want me to try?

**Comment by JC5** [comment]
Open your ``.env`` file and change ``APP_LOG_LEVEL=`` from whatever it is, to ``debug``.

That, or try to recreate the piggy bank.

Did you set a target date for the piggy bank, one which is now past?

**Comment by HomelessAvatar** [comment]
No target date was set.

I deleted and recreated the piggy bank per your suggestion.
It worked this time!

Thank you very much for your help and awesome work on this project!

**Comment by JC5** [comment]
You're welcome! Let me know if you run into any more problems!
