### ISSUE TITLE
Question regarding advance payments

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#423]
Hi,
I have a question about advance payments. I just did a transaction at the restaurant where I paid for my colleagues that joined as well.
They need to pay me back.
My idea is to create this transaction as a split transaction, a line for each of my colleagues and a line for my own food.
Now my colleagues will pay me back, each in their own transaction. How do I enter this in Firefly so my budget (and related stuff) is not affected?
I heard about the concept of balancing tags which is not fully clear to me, and I did not see the option to link a tag to a line of a split transaction.
Can you guide me in the correct direction?

Thanks!

**Comment by xzaz** [comment]
You didn't do a advance payment. You did a payment to the restaurant. So You -> Restaurant (this is what your bank shows you). Firefly has currently know option to use a 'reverse bill'. It's in the pipeline though.

**Comment by zjean** [comment]
I see in the [wiki](https://github.com/JC5/firefly-iii/wiki/Tags#advance-payment) something about it. Maybe I shouldn't use split transactions, but just add a tag to the 'main' transaction, and assign the tag to the deposits as well.
This however doesn't let me keep track on whom paid me back and who not. But that's maybe not Firefly's job :-(

**Comment by JC5** [comment]
At the moment, you don't.

The idea of an advance payment (which is what you should use) is that it contains one expense (your restaurant bill) and multiple deposits (your colleagues paying you back). It should show on your reports as being balanced out:

![screen shot 2016-11-25 at 15 42 59](https://cloud.githubusercontent.com/assets/5889984/20628376/df17e4e0-b325-11e6-82db-c525708ab33f.png)

If you do this in a split transaction, all the better. It adds clarity. It will not affect your budgets, nor will it change any views.

You're asking for two things:

1. To keep track of who paid you back.The page of the balancing-act tag (`/tag/show/x`) will show you exactly who paid you back and who didn't and the amount you're still out.
2. To balance budgets. That unfortunately, is not going to be a feature. I've experimented with it in the past and it's pretty complex: you need to accept "income" into a budget, which would either expand the budget to fit the large expense or somehow "lower" the amount of money spent in a budget (since this amount has been offset by the income). But both of these solutions distort the view of the budget. Having said that, not doing anything _also_ distorts this view, because a large expense makes it look like you're spending too much money, when in fact you are not.

A solution might be is to put your own restaurant bill on a budget, and the rest without a budget (inside the split transaction).  I'm pretty sure this is possible. If not, I should build it.

**Comment by JC5** [comment]
So create the restaurant bill as a split transaction. Give it the tag "I paid food". Make this tag an advance payment later

Splits:
50 spent by you in category "food" and budget "food"
50 spent for colleague A in category "food" and no budget
50 spent for colleague B in category "food" and no budget
50 spent for colleague C in category "food" and no budget
50 spent for colleague D in category "food" and no budget

Sum: 250. Expense in your own food-budget: 50. You're still out 200, which should come back to you in four deposits which you also tag "I paid food"

**Comment by zjean** [comment]
Thanks for the clarification! I will try this solution :-)

**Comment by zjean** [comment]
I have an additional question: When I add the tag to the main transaction like suggested, this transaction will never balance out, because my own expense for lunch was part of it as well. This will keep this tag 'open' forever, isn't it? 
Wouldn't it be good/nice to be able to link a tag to a splitted line? In that case I can give each colleague his own tag.
When the colleague pays his debt, I attach his 'own tag', which makes it also easier to outstanding  amounts per person.

**Comment by JC5** [comment]
No, the transaction will never balance out. That's something you cannot avoid. Ideally, the tag reflects what your share was.
