### ISSUE TITLE
Is it correct that import accounts show up in the search results

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#478]
Hi,
when searching for an account, I see that some accounts I didn't know they exist, show up.
They have a type of firefly.Import account.

What are they for, and should they show up here?

**Comment by JC5** [comment]
Good call! They shouldn't show up indeed. I'll make sure they won't be found. The "firefly." thing is an indication of a missing translation. Figures, because you're not supposed to see it.

To explain what they are: Since Firefly III is a double-entry bookkeeping system _every_ transaction needs a counter-part. That includes the very first opening balance for each account: accounts always start at zero and _then_ get their initial balance by a hidden transaction.

The opposite account for that transaction is also hidden. Except for in the search, it seems ;).

**Comment by zjean** [comment]
Thanks for your explanation!
I was just pulling the code and checking the results. It filters out the import accounts, however I get some strange result:
It seems that the ID of the account_type is used instead of the id of the transaction, because I get 404's when clicking the accounts in the search results.

**Comment by zjean** [comment]
Besides my last comment: I see that the initial balance accounts that are made by the importer are created with account type = Revenue account, while there is a account type Initial balance in the database. Is this intended behaviour?

**Comment by JC5** [comment]
The search has been fixed.

The initial balance account type is only used when you edit or create the account using the regular interface (using the initial balance field).

The importer will always assume the opposing account is an actual expense or revenue account.
