### ISSUE TITLE
Opening /accounts/expense throws exception

### ISSUE THREAD

**Issue by GumbalMumbal** [JC5/firefly-iii#482]
The error is as follows:

>  An exception has been thrown during the rendering of a template ("A non-numeric value encountered") in "list.accounts" at line 53.

Every other page I tested opens fine.

**Comment by JC5** [comment]
It seems there is a small piece of math on that page that fails in specific conditions. I will try to fix this tonight, otherwise tomorrow. In the mean time, a temporary fix you can apply yourself is to open the file at `resources/views/list/accounts.twig` and remove the content of line 54:

`{{ (account.endBalance - account.startBalance)|formatAmount }}`

Then, go to line **53** and change the data-value thing so it reads:

`data-value="0"`

Make sure you back up the file accounts.twig because you cannot upgrade at a later stage when the file is not in the original state.

When the new version of Firefly is released, copy the original file over your edits (re-enabling the bug) and then upgrade.

**Comment by GumbalMumbal** [comment]
Your fix works for me, thank you very much.

**Comment by JC5** [comment]
Cool! A
