### ISSUE TITLE
Can't get firefly-iii to work

### ISSUE THREAD

**Issue by Steephh** [JC5/firefly-iii#54]
I installed firefly-iii on Ubuntu 14.04-LTS with nginx and mysql (via ajenti). First I installed composer globally, then I followed the install guide. I got some errors when running 'php artisan migrate --seed --env=production', fixed that with adding "doctrine/dbal": "~2.3" into the composer.json. Now I run into some errors, but don't know how to track this down. I tried this with a empty database, if I run the command again it says several tables already exists.

These are the errors I run into now:

 [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1025 Error on rename of './firefly@002diii/#sql-3d7_34d2' to './firefly@002diii/limit_repetitions' (errno: 150) (SQL: ALTER TABLE limit_repetitions CHANGE limit_id budget_limit_id INT UNSIGNED NOT NULL)

  [PDOException]
  SQLSTATE[HY000]: General error: 1025 Error on rename of './firefly@002diii/#sql-3d7_34d2' to './firefly@002diii/limit_repetitions' (errno: 150)

**Comment by JC5** [comment]
I've tried it locally using a Vagrant box and it seems to work just fine, even though not all the tables are perfect yet. 

If the tables already exist, be sure to remove all tables first, before you run the migration command (``php artisan migrate --seed --env=production``) again.

I've done the following:

- I've updated composer.json to include doctrine/dbal. Thanks for the heads up!
- I've uploaded a reference SQL file. If nothing works, use that one. You can find it [here](https://github.com/JC5/firefly-iii/blob/develop/_sql/firefly-iii-reference-3.2.2.sql).
- I'm looking into missing foreign keys and references (``errno: 150`` is a reference to such errors).

Please see if the SQL file and/or another attempt at running the migration will work. I'll see if I can find anything on this side.

**Comment by Steephh** [comment]
Thanks for the quick reply! With the reference SQL file the migration seems to work. I receive no errors anymore with the migration command.

When trying to create a new account however, I only see the message: "Whoops, looks like something went wrong.". Do I try this again it says that the email-address has been taken.

I guess this has something to do with my e-mail settings, but is it possible to get a more useful error message?

**Comment by JC5** [comment]
At the moment, the error you see is a general "fallback" error which is used whenever something goes wrong. You should be able to find log files in the following directory:

``./app/storage/logs``

There, the last messages should explain what happened. Most often it's the e-mail configuration. There is no fallback for that one: if sending an email fails you cannot retrieve the password in another way. I will create another issue to fix that, because relying on e-mail isn't very useful.

If you want to see more debug information by default, you can edit ``./app/config/production/app.php`` and set the debug levels a tad higher:
```
<?php

return [
    'timezone'        => 'UTC',
    'key'             => md5('REPLACE ME'),
    'debug'             => true,
    'log_level'             => 'debug',
];
```

To re-register your own e-mail address, remove the single entry you should see in database table ``users``.
