### ISSUE TITLE
Import bank statements

### ISSUE THREAD

**Issue by Jerrik** [JC5/firefly-iii#59]
Have you thought of the ability to import bank statements? CSV's for example?

**Comment by JC5** [comment]
Absolutely, but so far it has proven to be difficult. Not the import as such. PHP supports CSV out of the box and even running big ones is fast and memory efficient.

The problem is that every single bank has a different format. Some list the description per line in four different fields. Others mention the amount by splitting it in coins and cents. There's all sorts of stuff out there.

Then, there's trying to catch double imports (which I now think of, could be done relatively easy) and catching "double" imports: you've created the entry in Firefly but you're importing it from your bank as well.

On the other hand, I've not yet looked into shared formats such as the Swift MT940 format. 

My own experience has taught me that most (if not all) entries need manual touching up after they're imported, which makes importing data only marginally more efficient than doing it by hand.

It is on my wish list and I'll keep this open to remind myself!

**Comment by JC5** [comment]
Hi Jerrik!

This is now possible.

**Comment by vDorst** [comment]
I made a simple python converter to convert ABN Amro CSV to well parsed data for Firefly.
All accountnumber are not IBAN but old number. So I have to convert them.
All the transactiondata are placed in the description in 5 differant formats.

Like:
SEPA PLAIN:  ```SEPA iDEAL                       IBAN: NL12RABO0121212212        BIC: RABONL2U                    Naam: Silver Ocean B.V.         Omschrijving: 1232138 1232131233 412321 iBOOD.com iBOOD.com B.V. Kenmerk: 01-10-2014 20:03 002000 0213123238```
TRTP ENCODED: ```/TRTP/SEPA OVERBOEKING/IBAN/NL23ABNA0000000000/BIC/ABNANL2A/NAME/baasd dsdsT CJ/REMI/Nullijn/EREF/NOTPROVIDED```
BEA and GEA: ```BEA   NR:00AJ01   31.01.01/11.54 Van HarenSchoenen,PAS123```
OLD Format:  ``` 12.21.22.222                    BNP aaaaaaa aaaaaa SCH          BETALINGSKENM.  2323233232323323 MAAND* APRIL 01                 REF* 1212121-42-41```
ABN AMRO Bank: ```ABN AMRO Bank N.V.               Prive pakket                3,25```

I detect and parse them with regexpresions.
After that I also place a catergory and budget label to it also via regexpresion with keywords.
So I put shop like Jumbo, Plus etc in category and budget Boodschappen.

I put all this data back in a CSV file for Firefly.

With my python script I can import the CSV file without to sort it anymore.

My Script https://gist.github.com/vDorst/68d555a6a90f62fec004

**Comment by JC5** [comment]
Cool cool cool.
