### ISSUE TITLE
CSV Sample File

### ISSUE THREAD

**Issue by alfa5** [JC5/firefly-iii#98]
Can you add a CSV sample file for import?

I am trying to import some transactions but always get the message:

>The CVS importer has finished and has processed 0 rows
> Firefly has created 0 new transaction(s).

**Comment by JC5** [comment]
Do you use ```,``` or ```;``` as field separation? Do you use newlines (```\n```) or carriage returns + new lines? (```\r\n```).

At the moment the importer only supports the first (```,``` and ```\n```).

The idea is that ANY (well... almost any) CSV file can be imported, because you can select what the content of each column is supposed to be.

Your error seems to indicate that FF was not able to find any rows in your CSV file. Also, I've spotted a small typo in that message.

**Comment by alfa5** [comment]
I use `,` and `\n`. Exsit some requiered fields that must be in the csv file?

This are the csv file and the configuartion file I use:
https://gist.github.com/alfa5/f189e4bdfbb9d8e6108b

**Comment by JC5** [comment]
It's a bug. I'll release a fix soon.

When a CSV file has headers (like yours), Firefly skips the first row after the headers.

For the time being, duplicate row number one (line #2 in your file) and run the file as usual.

**Comment by alfa5** [comment]
Thank you.

It work well when duplicate the row as you say.

**Comment by JC5** [comment]
Good! The fix will arrive with 3.4.11, after which duplicating the row will no longer be necessary.
